---
title: "Incorporating the geography from DANE for department and municipalities"
author: "Marius Bottin"
lang: es
format: 
  gfm:
    df-print: kable
knitr: 
  opts_chunk: 
    fig.path: "./Fig/Incor_DANE"
---

Natalia Medina gave me the 2023 geographic DANE version that I dowloaded on my local computer

```{r}
DIR_DATA <- "/home/marius/Travail/Data/DANE_geog_colombia/MGN 2023/"
dir(DIR_DATA)
require(sf)
dpto<-st_read(DIR_DATA,"MGN_DPTO_POLITICO_2023")
mpio<-st_read(DIR_DATA,"MGN_MPIO_POLITICO_2023")
st_crs(dpto)
st_crs(mpio)
head(dpto)
head(mpio)
table(mpio$mpio_tipo)
```

## Connect to the database

```{r}
pp_bst <- RPostgres::dbConnect(RPostgres::Postgres(), dbname = "pp_bst_col")
```

## Managing the reference systems

```{r}
(sridDB<-RPostgres::dbGetQuery(pp_bst,"SELECT srid FROM geometry_columns WHERE f_table_schema='main' GROUP BY srid ORDER BY count(*) DESC LIMIT 1")$srid)
dpto<-st_transform(dpto,sridDB)
mpio<-st_transform(mpio,sridDB)
```

## Creating the shemas

```{r}
schemas<-RPostgres::dbGetQuery(pp_bst,"SELECT schema_name FROM information_schema.schemata")$schema_name
if(!"tmp" %in% schemas)
{RPostgres::dbExecute(pp_bst,"CREATE schema tmp")}
if(!"spat" %in% schemas)
{RPostgres::dbExecute(pp_bst,"CREATE schema spat")}
```

## Creating the tables

```{r}
all(toupper(mpio$suggestedC)==mpio$mpio_cnmbr)
if(RPostgres::dbExistsTable(pp_bst,DBI::Id(schema="spat",table="mpio_dane_2023")))
{RPostgres::dbExecute(pp_bst,"DROP TABLE spat.mpio_dane_2023")}
if(RPostgres::dbExistsTable(pp_bst,DBI::Id(schema="spat",table="dpto_dane_2023")))
{RPostgres::dbExecute(pp_bst,"DROP TABLE spat.dpto_dane_2023")}
RPostgres::dbExecute(pp_bst,
"CREATE TABLE spat.dpto_dane_2023
(
  dpto_ccdgo char(2) PRIMARY KEY,
  dpto text UNIQUE
)")
RPostgres::dbExecute(pp_bst,paste0(
  "SELECT AddGeometryColumn('spat','dpto_dane_2023','the_geom',",RPostgres::dbQuoteLiteral(pp_bst,sridDB),",'MULTIPOLYGON',2,true)"))
RPostgres::dbExecute(pp_bst,
"CREATE TABLE spat.mpio_dane_2023
(
  mpio_cdpmp char(5) PRIMARY KEY,
  dpto_ccdgo char(2) REFERENCES spat.dpto_dane_2023(dpto_ccdgo),
  mpio text,
  UNIQUE(dpto_ccdgo,mpio)
)")
RPostgres::dbExecute(pp_bst,paste0(
  "SELECT AddGeometryColumn('spat','mpio_dane_2023','the_geom',",RPostgres::dbQuoteLiteral(pp_bst,sridDB),",'MULTIPOLYGON',2,true)"))
```

## Inserting the values in the table

```{r}
dpto<-dpto[,c("dpto_ccdgo","suggestedS","geometry")]
colnames(dpto)<-c("dpto_ccdgo","dpto","geometry")
st_geometry(dpto)<-"the_geom"
st_write(dpto,pp_bst,DBI::Id(schema="spat", table="dpto_dane_2023"),append=T)
```

```{r}
mpio<-mpio[,c("mpio_cdpmp","dpto_ccdgo","suggestedC","geometry")]
colnames(mpio)<-c("mpio_cdpmp","dpto_ccdgo","mpio","geometry")
st_geometry(mpio)<-"the_geom"
st_write(mpio,pp_bst,DBI::Id(schema="spat", table="mpio_dane_2023"),append=T)
```


## Shutting down light...

```{r}
RPostgres::dbDisconnect(pp_bst)
```


